# SPDX-License-Identifier: Apache-2.0
---
# RHEL 7 KB Note: https://access.redhat.com/discussions/3936201

# Select fapolicy type to configure. Options: 'generic', 'nw', 'hana'.
sap_fapolicy_type: 'generic'

# The user for fapolicy configuration.
# Mandatory when `sap_fapolicy_type` is set to 'generic'.
# Automatically set as `sap_fapolicy_sid` + 'adm' if `sap_fapolicy_type` is 'nw' or 'hana'.
sap_fapolicy_user: ''

# The User ID of provided user `sap_fapolicy_user`.
# Automatically set if `sap_fapolicy_user` or `sap_fapolicy_sid` is provided.
sap_fapolicy_uid: ''

# The SAP System ID (3 letter String).
# Mandatory when `sap_fapolicy_type` is set to 'nw' or 'hana'.
sap_fapolicy_sid: ''

# The list of directories for fapolicy configuration.
sap_fapolicy_directory_list:
  - "/hana/"
  - "/sapmnt/"
  - "/usr/sap/"
  - "/software/"
  - "/var/tmp/"
  - "/tmp/"

# The header line to add to fapolicy rules.
sap_fapolicy_rules_header: "# Allow rules for SAP directories"
