pyrfc_first_run: true

sap_nwrfc_sdk: nwrfc750P_8-70002752.zip

target_function: STFC_CONNECTION

target_parameters:
  REQUTEXT: "Hello SAP!"

target_connection:
  ashost: s4hana.poc.cloud
  sysid: TDT
  sysnr: "01"
  client: "400"
  user: DDIC
  passwd: Password1
  lang: EN
#  trace: 3
#  saprouter: /H/111.22.33.44/S/3299/W/e5ngxs/H/555.66.777.888/H/
#  gwhost: gateway.poc.cloud
#  ghserv: gateway.poc.cloud
