# SPDX-License-Identifier: Apache-2.0
---

# This variable defines all SAP systems, profiles, and parameters to be managed
# or updated on the current host. It is structured as a list of dictionaries,
# where each top-level dictionary defines a specific SAP System ID (SID).
#
# Structure:
# - List of Systems (sid)
#   - List of Profiles (type: default/instance)
#     - List of Parameters (name, value, state)
#
# Key fields:
# * sid: The 3-letter SAP System ID (e.g., 'PRD', 'QAS').
# * profiles: A list of profile files to manage for this SID.
#   * type: 'default' or 'instance'. Used for dynamic path calculation.
#   * instance_number: Required if type is 'instance' (e.g., '00', '10').
#   * path: (Optional) Explicit file path to the profile. If omitted, the path
#           will be constructed based on 'sid', 'type', and discovered facts.
#   * parameters: The list of parameters to apply to this profile file.
#     * name: Parameter name to update (e.g., 'ssl/ciphersuites').
#     * value: New value for the parameter. Not required if state is 'absent'.
#     * state: (Optional) 'present' (default) or 'absent'.
#
sap_profile_update_definitions: []


# Enable this variable to restart sapstartsrv service after updating parameters.
# This is applicable only for 'instance' type profiles as DEFAULT.PFL does not have sapstartsrv.
# This role does not manage restart of complete SAP System,
# and this parameter is limited to 'sapcontrol -function RestartService' only.
sap_profile_update_restart_sapstartsrv: false
