# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server 15

# NOTE: SLES 16 contains dependency between firewalld and python313-firewall package.

__sap_firewall_packages:
  - firewalld

__sap_firewall_extra_packages:
  "{{ __sap_firewall_extra_packages_3
    if ansible_facts['distribution_version'].split('.')[1] | int < 6
    else __sap_firewall_extra_packages_311 }}"

# The lists of bindings for specific python version
__sap_firewall_extra_packages_3:
  - "python3-firewall"

__sap_firewall_extra_packages_311:
  - "python311-firewall"
