---
# Amazon Simple Storage Service (S3)

- name: SAP HANA Backint - Execute - Set fact for SID
  ansible.builtin.set_fact:
    passed_sap_hana_sid: "{{ sap_hana_sid }}"
  when: sap_hana_sid != "all"

# Set initial facts
- name: SAP HANA Backint - Setup - AWS S3 - Set facts
  ansible.builtin.set_fact:
    sap_hana_backint_setup_backint_directory: "/usr/sap/{{ passed_sap_hana_sid }}/SYS/global/hdb/opt"
    passed_sap_hana_instance_nr: "{{ sap_hana_instance_nr_one[0] }}"

- name: SAP HANA Backint - Setup - AWS S3 - Discover tar.gz of SAP HANA Backint Agent for Amazon S3
  ansible.builtin.find:
    paths: "/"
    recurse: true
    patterns: "aws-s3-backint-*.tar.gz"
  register: __sap_hana_backint_agent_s3_targz

- name: SAP HANA Backint - Setup - AWS S3 - Output tar.gz path of SAP HANA Backint Agent for Amazon S3
  ansible.builtin.debug:
    msg: "{{ __sap_hana_backint_agent_s3_targz.files[0].path }}"

- name: SAP HANA Backint - Setup - AWS S3 - Extract tar.gz of SAP HANA Backint Agent for Amazon S3
  ansible.builtin.unarchive:
    src: "{{ __sap_hana_backint_agent_s3_targz.files[0].path }}"
    dest: "{{ sap_hana_backint_setup_temp_dir.path }}"
    remote_src: true

- name: SAP HANA Backint - Setup - AWS S3 - Discover binary of SAP HANA Backint Agent for Amazon S3
  ansible.builtin.find:
    paths: "{{ sap_hana_backint_setup_temp_dir.path }}"
    recurse: true
    file_type: directory
    patterns: "aws-s3-backint"
  register: __sap_hana_backint_agent_s3

- name: SAP HANA Backint - Setup - AWS S3 - Output binary path of SAP HANA Backint Agent for Amazon S3
  ansible.builtin.debug:
    msg: "{{ __sap_hana_backint_agent_s3.files[0].path }}"

# src must end in forward-slash / to copy directory contents - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-src
- name: SAP HANA Backint - Setup - AWS S3 - Copy temp directory contents to SAP HANA Backint directory
  ansible.builtin.copy:
    src: "{{ __sap_hana_backint_agent_s3.files[0].path }}/"
    dest: "{{ sap_hana_backint_setup_backint_directory }}"
    mode: "0755"
    directory_mode: true
    remote_src: true

# Change directory owner and permission
- name: SAP HANA Backint - Setup - AWS S3 - Change directory owner and permission
  ansible.builtin.file:
    path: "{{ sap_hana_backint_setup_backint_directory }}"
    state: directory
    recurse: true
    mode: "0755"
    owner: "{{ passed_sap_hana_sid | lower }}adm"
    group: sapsys

- name: SAP HANA Backint - Setup - AWS S3 - Set fact for backint file
  ansible.builtin.set_fact:
    sap_hana_backint_setup_backint_file: "{{ sap_hana_backint_setup_backint_directory }}/hdbbackint"

# Setup

- name: SAP HANA Backint - Setup - AWS S3 - Clone hanacleaner.py
  ansible.builtin.git:
    repo: https://github.com/chriselswede/hanacleaner.git
    dest: "$HOME/.ansible/tmp/git_hanacleaner"
    single_branch: true
    version: master

# Copy hanacleaner.py
- name: SAP HANA Backint - Setup - AWS S3 - Copy hanacleaner.py to SAP HANA backint directory
  ansible.builtin.copy:
    src: "$HOME/.ansible/tmp/git_hanacleaner/hanacleaner.py"
    dest: "{{ sap_hana_backint_setup_backint_directory }}/hanacleaner.py"
    mode: "0755"
    remote_src: true
  register: hdbbackint_hanacleaner

# Softlink Python
- name: SAP HANA Backint - Setup - AWS S3 - Create softlink of {{ python_37_binary }} into {{ sap_hana_backint_setup_backint_directory }}
  ansible.builtin.file:
    src: "{{ python_37_binary }}"
    dest: "{{ sap_hana_backint_setup_backint_directory }}/python37_alt"
    owner: "{{ passed_sap_hana_sid | lower }}adm"
    group: sapsys
    state: link
  register: python_37_binary_hana_dir

- name: SAP HANA Backint - Setup - AWS S3 - Set fact for Python altinstall
  ansible.builtin.set_fact:
    python_37_binary_hana_softlink: "{{ python_37_binary_hana_dir.dest }}"

- name: SAP HANA Backint - Setup - AWS S3 - Replace hdbbackint launch script
  ansible.builtin.template:
    src: "{{ role_path }}/templates/hdbbackint.j2"
    dest: "{{ sap_hana_backint_setup_backint_file }}"
    mode: "0755"

# Softlink hdbbackint
# - name: SAP HANA Backint - Setup - AWS S3 - {{ sap_hana_backint_setup_backint_file }} {{ sap_hana_backint_setup_backint_directory }}/hdbbackint
#   ansible.builtin.file:
#     src: "{{ sap_hana_backint_setup_backint_file }}"
#     dest: "{{ sap_hana_backint_setup_backint_directory }}/hdbbackint"
#     owner: "{{ passed_sap_hana_sid | lower }}adm"
#     group: sapsys
#     state: link

# Process hdbbackint.cfg
- name: SAP HANA Backint - Setup - AWS S3 - Process hdbbackint.cfg
  ansible.builtin.template:
    src: "{{ role_path }}/templates/aws_s3_hdbbackint.cfg"
    dest: "{{ sap_hana_backint_setup_backint_directory }}/hdbbackint.cfg"
    mode: "0644"
  register: hdbbackint_template

# Change directory owner and permission
- name: SAP HANA Backint - Setup - AWS S3 - Change directory owner and permission
  ansible.builtin.file:
    path: "{{ sap_hana_backint_setup_backint_directory }}"
    state: directory
    recurse: true
    mode: "0755"
    owner: "{{ passed_sap_hana_sid | lower }}adm"
    group: sapsys

- name: SAP HANA Backint - Setup - AWS S3 - Output backint configuration information
  ansible.builtin.debug:
    msg:
      - "backint directory  - {{ sap_hana_backint_setup_backint_directory }}"
      - "backint file       - {{ sap_hana_backint_setup_backint_file }}"
      - "backint cfg        - {{ sap_hana_backint_setup_backint_directory }}/hdbbackint.cfg"
      - "backint link       - {{ sap_hana_backint_setup_backint_directory }}/hdbbackint"
