---
- name: Wait for status to change if using restart or update
  when: funct_type is match('restart|update')
  block:
    - name: SAP {{ sap_control_name_header }} - Getting current system state
      ansible.builtin.shell: |
        source ~/.profile && sapcontrol -nr {{ passed_sap_nr }} -function {{ async_function_dict.test_function }}
      args:
        executable: /bin/bash
      become: true
      become_user: "{{ passed_sap_sid | lower }}adm"
      register: initial_test_function_result

    - name: SAP {{ sap_control_name_header }} - Waiting for state to change before polling
      ansible.builtin.shell: |
        source ~/.profile && sapcontrol -nr {{ passed_sap_nr }} -function {{ async_function_dict.test_function }}
      args:
        executable: /bin/bash
      become: true
      become_user: "{{ passed_sap_sid | lower }}adm"
      register: wait_for_change_result
      retries: "{{ async_function_dict.retries | default(0) | int }}"
      delay: "{{ async_function_dict.delay | default(0) | int }}"
      until: >
        (wait_for_change_result.stdout | regex_findall('GREEN|YELLOW|GRAY|RED', multiline=True)  | sort | join(','))
        != (initial_test_function_result.stdout | regex_findall('GREEN|YELLOW|GRAY|RED', multiline=True)  | sort | join(','))

- name: Pause for 20 Seconds to ensure the async function is started
  ansible.builtin.wait_for:
    timeout: 20

- name: SAP {{ sap_control_name_header }} - Checking if Async action is over by executing sapcontrol -nr {{ passed_sap_nr }} -function {{ async_function_dict.test_function }}
  ansible.builtin.shell: |
    source ~/.profile && sapcontrol -nr {{ passed_sap_nr }} -function {{ async_function_dict.test_function }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_sid | lower }}adm"
  register: test_function_result
  retries: "{{ async_function_dict.retries | default(0) | int }}"
  delay: "{{ async_function_dict.delay | default(0) | int }}"
  until: >
    (async_function_dict.until_false is not defined
    or async_function_dict.until_false is defined
    and test_function_result.stdout | regex_search(async_function_dict.until_false, multiline=True) is none) and
    (async_function_dict.until_true is not defined or
    async_function_dict.until_true is defined
    and test_function_result.stdout | regex_search(async_function_dict.until_true, multiline=True) is not none)

- name: Debug stdout
  ansible.builtin.debug:
    msg: |
       Async function {{ async_function_dict.test_function }} for SAP SID {{ passed_sap_sid }}
       is done with result:
       {{ test_function_result.stdout }}
