# SPDX-License-Identifier: Apache-2.0
---

# Name of existing Secondary Node that will Takeover current Primary Node (String).
# This name must exist in playbook hosts.
sap_hana_sr_takeover_primary: ''

# SAP HANA Database System ID (SID) in capital letters (String).
sap_hana_sr_takeover_sid: ''

# SAP HANA Database Instance Number (String).
sap_hana_sr_takeover_instance_number: ''

# SAP HANA System Replication mode that will be applied during registration (String).
# Available values: sync, syncmem, async
sap_hana_sr_takeover_replication_mode: sync

# SAP HANA System Replication Operation mode that will be applied during registration (String).
# Available values: delta_datashipping, logreplay, logreplay_readaccess
sap_hana_sr_takeover_operation_mode: logreplay

# The path to the shell environment file for the <sid>adm user (String).
# Used to source environment variables before executing SAP-specific commands.
# If not set, it defaults to: '/usr/sap/{{ sap_hana_sr_takeover_sid | lower }}/home/.profile'
# sap_hana_sr_takeover_sidadm_env_file_path: ''
