---
galaxy_info:
  namespace: community
  author: IBM Lab for SAP Solutions, Red Hat for SAP Community of Practice, Sean Freeman
  description: Execute SAP Remote Function Call (RFC)
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [7, 8, 9]
    - name: SLES
      versions: [15SP3]
  galaxy_tags: ['sap', 'rfc', 'pyrfc', 'rhel', 'redhat', 'sles', 'suse']
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
collections:
- community.sap_libs
- community.sap_launchpad
