---
# SPDX-License-Identifier: Apache-2.0

# Reload is skipped when firewalld service is set to disabled.
- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  when: sap_firewall_end_status == 'enabled' | d('enabled')
  changed_when: true
