# Restart sapstartsrv

# Get number of sapstartsrv processes running for {{ passed_sap_sid }}-{{ passed_sap_nr }}
- name: SAPstartsrv - Get number of sapstartsrv processes running for {{ passed_sap_sid }}-{{ passed_sap_nr }}
  ansible.builtin.shell: |
    ps -ef | grep {{ passed_sap_sid }} | grep {{ passed_sap_nr }} | grep sapstartsrv | awk '{ print $8 }'
  register: num_of_sapstartsrv_reg

- name: SAPstartsrv - Set fact for number of sapstartsrv
  ansible.builtin.set_fact:
    num_of_sapstartsrv: "{{ num_of_sapstartsrv_reg.stdout.split() }}"

# Stop sapstartsrv
- name: SAPstartsrv - Stop sapstartsrv {{ passed_sap_sid }}-{{ passed_sap_nr }}
  ansible.builtin.shell: |
    source ~/.profile && cdexe; sapcontrol -nr {{ passed_sap_nr }} -function StopService {{ passed_sap_sid }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_sid | lower }}adm"
  register: sap_stop_sapstartsrv
  loop: "{{ num_of_sapstartsrv }}"
  delay: 2

# Start sapstartsrv
- name: SAPstartsrv - Start sapstartsrv {{ passed_sap_sid }}-{{ passed_sap_nr }}
  ansible.builtin.shell: |
    source ~/.profile && cdexe; sapcontrol -nr {{ passed_sap_nr }} -function StartService {{ passed_sap_sid }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_sid | lower }}adm"
  register: sap_start_sapstartsrv

- name: SAPstartsrv - Wait for 10 seconds for sapstartsrv to initialize
  ansible.builtin.pause:
    seconds: 10
