---
sap_sid: "initial"
sap_control_function: "initial"
sap_control_name_header: "initial"

nowait: false
sap_control_start: "StartWait 180 2"
sap_control_stop: "StopWait 180 2"
sap_control_startsystem: "StartSystem ALL 180"  # function StartSystem waittimeout
sap_control_stopsystem: "StopSystem ALL 180 480"  # function StopSystem waittimeout softtimeout
sap_control_restartsystem: "RestartSystem ALL 180 480"  # function RestartSystem waittimeout softtimeout
sap_control_updatesystem: "UpdateSystem 180 480 0"  # function UpdateSystem waittimeout softtimeout force
sap_control_waitforstopped: "WaitforStopped 180 2"  # function WaitforStopped waittimeout delay
sap_control_waitforstarted: "WaitforStarted 180 2"  # function WaitforStarted waittimeout delay

# Parameters to handle async functions in sapcontrol_async.yml

sap_control_startsystem_waitforasync:
  test_function: "GetSystemInstanceList"
  retries: 60
  delay: 10
  until_false: 'GRAY\s*$|RED\s*$|YELLOW\s*$'
  until_true: 'GREEN\s*$'

sap_control_restartsystem_waitforasync:
  test_function: "GetSystemInstanceList"
  retries: 60
  delay: 10
  until_false: 'GRAY\s*$|RED\s*$|YELLOW\s*$'
  until_true: 'GREEN\s*$'

sap_control_stopsystem_waitforasync:
  test_function: "GetSystemInstanceList"
  retries: 60
  delay: 10
  until_false: 'GREEN\s*$|RED\s*$|YELLOW\s*$'
  until_true: 'GRAY\s*$'

sap_control_updatesystem_waitforasync:
  test_function: "GetSystemUpdateList"
  retries: 60
  delay: 10
  until_false: 'GRAY\s*$|RED\s*$|YELLOW\s*$|GREEN\s*$'

# get_all_sap_sid_dir_nw: "/sapmnt"
# get_all_sap_sid_dir_hana: "/hana/shared"

# Sort Order to start SAP instances defined by SAP and recommended by SAP Basis Administrators
sap_control_instance_type_sortorder:
  - "HDB"
  - "ERS"
  - "ASCS"
  - "SCS"
  - "PAS"
  - "Java"
  - "WebDisp"

# Functions
sap_control_functions_list:
  - restartsystem_all_nw
  - updatesystem_all_nw
  - startsystem_all_nw
  - stopsystem_all_nw
  - restartsystem_sap_nw
  - updatesystem_sap_nw
  - startsystem_sap_nw
  - stopsystem_sap_nw
  - restart_all_sap
  - stop_all_sap
  - start_all_sap
  - restart_all_nw
  - restart_all_hana
  - stop_all_nw
  - start_all_nw
  - stop_all_hana
  - start_all_hana
  - restart_sap_nw
  - restart_sap_hana
  - stop_sap_nw
  - start_sap_nw
  - stop_sap_hana
  - start_sap_hana


# Functions flow
restartsystem_all_nw_list:
  - sap_control_function_current: "nw_restartsystem"

startsystem_all_nw_list:
  - sap_control_function_current: "nw_startsystem"

stopsystem_all_nw_list:
  - sap_control_function_current: "nw_stopsystem"

updatesystem_all_nw_list:
  - sap_control_function_current: "nw_startsystem"
  - sap_control_function_current: "nw_updatesystem"

restart_all_sap_list:
  - sap_control_function_current: "nw_stop"
  - sap_control_function_current: "hana_stop"
  - sap_control_function_current: "hana_start"
  - sap_control_function_current: "nw_start"

stop_all_sap_list:
  - sap_control_function_current: "nw_stop"
  - sap_control_function_current: "hana_stop"

start_all_sap_list:
  - sap_control_function_current: "hana_start"
  - sap_control_function_current: "nw_start"

restart_all_nw_list:
  - sap_control_function_current: "nw_stop"
  - sap_control_function_current: "nw_start"

restart_all_hana_list:
  - sap_control_function_current: "hana_stop"
  - sap_control_function_current: "hana_start"

stop_all_nw_list:
  - sap_control_function_current: "nw_stop"

start_all_nw_list:
  - sap_control_function_current: "nw_start"

stop_all_hana_list:
  - sap_control_function_current: "hana_stop"

start_all_hana_list:
  - sap_control_function_current: "hana_start"

restart_sap_nw_list:
  - sap_control_function_current: "nw_stop"
  - sap_control_function_current: "nw_start"

restart_sap_hana_list:
  - sap_control_function_current: "hana_stop"
  - sap_control_function_current: "hana_start"

stop_sap_nw_list:
  - sap_control_function_current: "nw_stop"

start_sap_nw_list:
  - sap_control_function_current: "nw_start"

stop_sap_hana_list:
  - sap_control_function_current: "hana_stop"

start_sap_hana_list:
  - sap_control_function_current: "hana_start"
